module.exports = {
  'todo-1': {
    name: 'Finish variables',
    desc: 'Use past sass projects for inspo.',
    category: 'design',
    link: '',
    complete: false,
  },
  'todo-2': {
    name: 'React Router Transitions',
    desc: 'Animate page transitioning in and out',
    category: 'design',
    link: '',
    complete: false,
  },
  'todo-3': {
    name: 'Animate Active Link',
    desc: 'Arrows going in and out on click',
    category: 'design',
    link: '',
    complete: false,
  },
  'todo-4': {
    name: 'Modernizr integration',
    desc: 'Make sure it looks the same on most browsers',
    category: 'component',
    link: '',
    complete: false,
  },
  'todo-5': {
    name: 'Flexbox',
    desc: 'Use flexbox for internal element layout',
    category: 'design',
    link: '',
    complete: false,
  },
  'todo-6': {
    name: 'CSS Grid layout',
    desc: 'Use grid for main layout',
    category: 'design',
    link: '',
    complete: false,
  },
  'todo-7': {
    name: 'Tagline powerline',
    desc: 'Set up powerline-like arrows and colors for the tagline',
    category: 'design',
    link: '',
    complete: false,
  },
  'todo-8': {
    name: 'Firebase Database',
    desc: 'Get database working for projects, skills, and todo',
    category: 'backend',
    link: '',
    complete: false,
  },
};
